### PR TITLE
DLPX-85172 update bpftrace to latest

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
`ab-pre-push` with https://github.com/delphix/linux-pkg/pull/279 is [here](http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/4780/)

**Review by sdimitro — APPROVED** [review]

**Comment by sdimitro** [comment]
This is great Prakash! I just checked the VM - here is bpftrace leveraging the BTF data with the environment variable to print type info:
```
delphix@ip-10-110-240-110:~$ sudo bpftrace -lv "struct path"
delphix@ip-10-110-240-110:~$ sudo BPFTRACE_BTF=/sys/kernel/btf/vmlinux bpftrace -lv "struct path"
struct path {
	struct vfsmount *mnt;
	struct dentry *dentry;
};
```

and here it is again using types without including header in a one-liner just like DTrace (first prompt is the error that we get if we don't set the BTF variable):

```
$ sudo bpftrace -e 'kprobe:vfs_open { printf("open path: %s\n", str(((struct path *)arg0)->dentry->d_name.name)); }'
stdin:1:45-65: ERROR: Unknown struct/union: 'struct path'
kprobe:vfs_open { printf("open path: %s\n", str(((struct path *)arg0)->dentry->d_name.name)); }
                                            ~~~~~~~~~~~~~~~~~~~~
stdin:1:45-93: ERROR: str() expects an integer or a pointer type as first argument (none provided)
kprobe:vfs_open { printf("open path: %s\n", str(((struct path *)arg0)->dentry->d_name.name)); }
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

delphix@ip-10-110-240-110:~$ sudo BPFTRACE_BTF=/sys/kernel/btf/vmlinux bpftrace -e 'kprobe:vfs_open { printf("open path: %s\n", str(((struct path *)arg0)->dentry->d_name.name)); }'
Attaching 1 probe...
open path: fd
open path: systemctl
open path: ld-2.31.so
open path: ld.so.cache
open path: libc-2.31.so
open path: libselinux.so.1
open path: liblzma.so.5.2.4
open path: liblz4.so.1.9.2
open path: libblkid.so.1.1.0
open path: libgcrypt.so.20.2.5
open path: libpthread-2.31.so
open path: libpcre2-8.so.0.9.0
^C
```

**Review by ahrens — APPROVED** [review]
I assume that we don't care about the "codeowners" being ignored?

**Comment by prakashsurya** [comment]
> I assume that we don't care about the "codeowners" being ignored?

what codeowners are you talking about? I don't see one..?

**Comment by ahrens** [comment]
image
I noticed because it's the first thing listed in files changed

**Pull request merged**
