### PR TITLE
Automatically include ZFS paths when they exists

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by pzakha** [comment]
I like this, this makes it easier to run one liner `bpftrace` scripts when debugging without worrying about wrappers.

**Comment by ahrens** [comment]
I like this too.  I think it's a good improvement in spite of the upgrade issue you mentioned in https://github.com/delphix/zfs/pull/95#discussion_r339693789

**Comment by prakashsurya** [comment]
I've tested this via `git-linux-pkg` to build and install these changes, and then tested using my "taskqlatency" bpftrace script:
```
$ sudo bpftrace taskqlatency.bt
Attaching 6 probes...
^C


@exec_lat_us[z_rd_int, zio_execute]:
[256, 512)             1 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|

@exec_lat_us[z_ioctl_int, zio_execute]:
[4, 8)                 3 |@@@@@@@@@@@@@@@@@@@                                 |
[8, 16)                8 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|

@exec_lat_us[z_wr_int_h, zio_execute]:
[8, 16)                8 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
[16, 32)               3 |@@@@@@@@@@@@@@@@@@@                                 |

@exec_lat_us[z_wr_iss_h, zio_execute]:
[16, 32)               3 |@@@@@@@@@@@@@@@@@@@                                 |
[32, 64)               8 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|

@queue_lat_us[z_rd_int]:
[8, 16)                1 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|

@queue_lat_us[z_ioctl_int]:
[4, 8)                 9 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
[8, 16)                2 |@@@@@@@@@@@                                         |

@queue_lat_us[z_wr_int_h]:
[4, 8)                 5 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@         |
[8, 16)                6 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|

@queue_lat_us[z_wr_iss_h]:
[4, 8)                 2 |@@@@@@@@@@@@@@@@@                                   |
[8, 16)                6 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
[16, 32)               3 |@@@@@@@@@@@@@@@@@@@@@@@@@@                          |
```

I'll mark this as "ready for review".. let me know if there's anything else that I need to do, to get this integrated.

**Review by pzakha — APPROVED** [review]
LGTM, pending ab-pre-push.

**Comment by prakashsurya** [comment]
`git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2383/)

**Comment by prakashsurya** [comment]
`git-ab-pre-push` has passed; what's next to get this landed?

**Pull request merged**
